# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8377d6ac20ded132987de90089736fd37925616dd7c398d8cfe201bcb0f89178324f6ac9d02750524886cec134bebb5b4354281b33a36a5872cc9bd88148a8d1

test:
  secret_key_base: 85ceea8fcf0b335013eba694c459523eca0f81c413e8ee87646aaec4a8adbc9103ea5184fa620945499af1a0100cbd07eb4deb1743456d7dcbb35f5055f55816

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
